version: "3.9"

services:
  db:
    image: postgres:15
    container_name: sincov_db
    restart: always
    environment:
      POSTGRES_USER: sincov_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: sincov_db

      TZ: America/Bogota
      PGTZ: America/Bogota
      
    ports:
      - "5432:5432"
    volumes:
      - sincov_db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: sincov_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"


volumes:
  sincov_db_data:
